url: "https://miguelbenitezrueda.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Miguel Ben√≠tez Rueda" # the name of your site, e.g. ACME Corp.
description: "Pre-doctoral Research Fellow, Inter-American Development Bank"
